# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2016


# メッセージの言語（ja = 日本語、en = 英語）
lang: 'ja'

# 対戦の開始と終了を、サーバー全体メッセージで通知するかどうか
broadcastSessionStartEnd: false

# ゲーム終了してから、テレポートして元の場所に戻るまでの、待ち時間（秒）
sessionEndWaitSeconds: 15
