# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2016


# Message locale. en = English, ja = Japanese, zh = Simplified Chinese.
lang: 'en'

# Send session start and end notification message as server broadcast.
broadcastSessionStartEnd: true

# The worlds that player cannot start the reversi game session.
# ex) prohibitWorlds: ['skyblock']
prohibitWorlds: []

# The wait seconds, from session ends, to teleport back.
sessionEndWaitSeconds: 15

# Enable/disable inventory switching system.
enableTemporaryInventory: false


# -------------------- Bet Reward Settings --------------------

# Bet and reward types.
# NONE -> Disable bets and rewards.
# ITEM -> Enable bet items and reward items.
# ECO -> Enable bet money and reward money.
#        If you want to use ECO feature, you need to use Vault and one of Economy plugin.
betRewardType: NONE

versusBetItem: DIAMOND
versusRewardItem: DIAMOND-2
easyBetItem: WOOD-2
easyRewardItem: WOOD-5
normalBetItem: IRON_INGOT-2
normalRewardItem: IRON_INGOT-5
hardBetItem: DIAMOND-2
hardRewardItem: DIAMOND-5

versusBetEco: 10
versusRewardEco: 20
easyBetEco: 3
easyRewardEco: 7
normalBetEco: 5
normalRewardEco: 12
hardBetEco: 8
hardRewardEco: 19
