# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2016


# Message locale.
lang: 'en'

# Send session start and end notification message as server broadcast.
broadcastSessionStartEnd: true

# The worlds that player cannot start the reversi game session.
# ex) prohibitWorlds: ['skyblock']
prohibitWorlds: []

# The wait seconds, from session ends, to teleport back.
sessionEndWaitSeconds: 15
